// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from '@hey-api/client-axios';
import type { NewsGetPagedListData, NewsGetPagedListError, NewsGetPagedListResponse, NewsCategoryGetPagedListError, NewsCategoryGetPagedListResponse, NewsCategoryCreateData, NewsCategoryCreateError, NewsCategoryCreateResponse, NewsCategoryUpdateData, NewsCategoryUpdateError, NewsCategoryUpdateResponse, NewsCategoryGetByIdData, NewsCategoryGetByIdError, NewsCategoryGetByIdResponse, NewsCategoryRemoveData, NewsCategoryRemoveError, NewsCategoryRemoveResponse, NewsSignatureGetPagedListError, NewsSignatureGetPagedListResponse, NewsSignatureCreateData, NewsSignatureCreateError, NewsSignatureCreateResponse, NewsSignatureUpdateData, NewsSignatureUpdateError, NewsSignatureUpdateResponse, NewsSignatureGetByIdData, NewsSignatureGetByIdError, NewsSignatureGetByIdResponse, NewsSignatureRemoveData, NewsSignatureRemoveError, NewsSignatureRemoveResponse, NewsTagGetPagedListError, NewsTagGetPagedListResponse, UploadsGetFileError, UploadsGetFileResponse, UploadsGetFile2Error, UploadsGetFile2Response } from './types.gen';

export class NewsService {
    public static newsGetPagedList(options?: Options<NewsGetPagedListData>) {
        return (options?.client ?? client).get<NewsGetPagedListResponse, NewsGetPagedListError>({
            ...options,
            url: '/admin/api/News'
        });
    }
    
}

export class NewsCategoryService {
    public static newsCategoryGetPagedList(options?: Options) {
        return (options?.client ?? client).get<NewsCategoryGetPagedListResponse, NewsCategoryGetPagedListError>({
            ...options,
            url: '/admin/api/NewsCategory'
        });
    }
    
    public static newsCategoryCreate(options?: Options<NewsCategoryCreateData>) {
        return (options?.client ?? client).post<NewsCategoryCreateResponse, NewsCategoryCreateError>({
            ...options,
            url: '/admin/api/NewsCategory'
        });
    }
    
    public static newsCategoryUpdate(options?: Options<NewsCategoryUpdateData>) {
        return (options?.client ?? client).put<NewsCategoryUpdateResponse, NewsCategoryUpdateError>({
            ...options,
            url: '/admin/api/NewsCategory'
        });
    }
    
    public static newsCategoryGetById(options: Options<NewsCategoryGetByIdData>) {
        return (options?.client ?? client).get<NewsCategoryGetByIdResponse, NewsCategoryGetByIdError>({
            ...options,
            url: '/admin/api/NewsCategory/{id}'
        });
    }
    
    public static newsCategoryRemove(options: Options<NewsCategoryRemoveData>) {
        return (options?.client ?? client).delete<NewsCategoryRemoveResponse, NewsCategoryRemoveError>({
            ...options,
            url: '/admin/api/NewsCategory/{id}'
        });
    }
    
}

export class NewsSignatureService {
    public static newsSignatureGetPagedList(options?: Options) {
        return (options?.client ?? client).get<NewsSignatureGetPagedListResponse, NewsSignatureGetPagedListError>({
            ...options,
            url: '/admin/api/NewsSignature'
        });
    }
    
    public static newsSignatureCreate(options?: Options<NewsSignatureCreateData>) {
        return (options?.client ?? client).post<NewsSignatureCreateResponse, NewsSignatureCreateError>({
            ...options,
            url: '/admin/api/NewsSignature'
        });
    }
    
    public static newsSignatureUpdate(options?: Options<NewsSignatureUpdateData>) {
        return (options?.client ?? client).put<NewsSignatureUpdateResponse, NewsSignatureUpdateError>({
            ...options,
            url: '/admin/api/NewsSignature'
        });
    }
    
    public static newsSignatureGetById(options: Options<NewsSignatureGetByIdData>) {
        return (options?.client ?? client).get<NewsSignatureGetByIdResponse, NewsSignatureGetByIdError>({
            ...options,
            url: '/admin/api/NewsSignature/{id}'
        });
    }
    
    public static newsSignatureRemove(options: Options<NewsSignatureRemoveData>) {
        return (options?.client ?? client).delete<NewsSignatureRemoveResponse, NewsSignatureRemoveError>({
            ...options,
            url: '/admin/api/NewsSignature/{id}'
        });
    }
    
}

export class NewsTagService {
    public static newsTagGetPagedList(options?: Options) {
        return (options?.client ?? client).get<NewsTagGetPagedListResponse, NewsTagGetPagedListError>({
            ...options,
            url: '/admin/api/NewsTag'
        });
    }
    
}

export class UploadsService {
    public static uploadsGetFile(options?: Options) {
        return (options?.client ?? client).get<UploadsGetFileResponse, UploadsGetFileError>({
            ...options,
            url: '/Uploads/GetFile'
        });
    }
    
    public static uploadsGetFile2(options?: Options) {
        return (options?.client ?? client).get<UploadsGetFile2Response, UploadsGetFile2Error>({
            ...options,
            url: '/Uploads/GetFile2'
        });
    }
    
}