// This file is auto-generated by @hey-api/openapi-ts

export type ApiErrorResponse = {
    message?: string | null;
    details?: string | null;
};

export type ApiSuccessResponse = {
    message?: string | null;
    details?: string | null;
};

export type IPagingState = {
    readonly indexFrom: number;
    readonly pageIndex: number;
    readonly pageSize: number;
    readonly totalCount: number;
    readonly totalPages: number;
    readonly hasPreviousPage: boolean;
    readonly hasNextPage: boolean;
};

export type MiniatureImageDto = {
    title: string;
    author: string | null;
    imageSourceUri: string;
    imageMiniatureUri: string;
    imageMiniaturePillarboxedUri: string;
};

export type NewsCategoryListItemDto = {
    id: string;
    title: string;
    published: boolean;
    itemsCount: number;
    createdBy: string;
    updatedBy: string;
    createdOnUtc: string;
    updatedOnUtc: string;
    mainPageBottomSlider: boolean;
    rightPanel: boolean;
    filterVisible: boolean;
    order: number;
};

export type NewsCategoryListItemDtoIPagedList = {
    state: IPagingState;
    readonly items: Array<NewsCategoryListItemDto>;
};

export type NewsCategoryShortDto = {
    id: string;
    title: string;
};

export type NewsListItemDto = {
    id: string;
    title: string;
    announcement: string;
    miniature?: MiniatureImageDto;
    category: NewsCategoryShortDto;
    tags: Array<NewsTagShortDto>;
    signature?: NewsSignatureShortDto;
    publishedOnUtc: string;
    imagesCount: number;
    visitsCount: number;
    pageName: string;
    videoTagsCount: number;
    audioTagsCount: number;
};

export type NewsListItemDtoIPagedList = {
    state: IPagingState;
    readonly items: Array<NewsListItemDto>;
};

export type NewsSignatureCreateDto = {
    title: string;
    shortTitle: string;
    published: boolean;
    isVisibleInFilter: boolean;
    order: number;
};

export type NewsSignatureListItemDto = {
    id: string;
    title: string;
    published: boolean;
    itemsCount: number;
    createdBy: string;
    updatedBy: string;
    createdOnUtc: string;
    updatedOnUtc: string;
    filterVisible: boolean;
    order: number;
};

export type NewsSignatureListItemDtoIPagedList = {
    state: IPagingState;
    readonly items: Array<NewsSignatureListItemDto>;
};

export type NewsSignatureShortDto = {
    id: string;
    title: string;
};

export type NewsSignatureUpdateDto = {
    id: string;
    title: string;
    shortTitle: string;
    published: boolean;
    isVisibleInFilter: boolean;
    order: number;
};

export type NewsTagListItemDto = {
    id: string;
    title: string;
    published: boolean;
    itemsCount: number;
    createdBy: string;
    updatedBy: string;
    createdOnUtc: string;
    updatedOnUtc: string;
    visibleOnlyInside: boolean;
    order: number;
};

export type NewsTagListItemDtoIPagedList = {
    state: IPagingState;
    readonly items: Array<NewsTagListItemDto>;
};

export type NewsTagShortDto = {
    id: string;
    title: string;
};

export type QueryOrder = 'Title' | 'PublishedOn' | 'Random';

export type QueryOrderDirection = 'Ascending' | 'Descending';

export type NewsGetPagedListData = {
    categoryTitle?: string;
    dateFrom?: string;
    dateTo?: string;
    minAudioCount?: number;
    minVideoCount?: number;
    onBanner?: boolean;
    onHome?: boolean;
    order?: QueryOrder;
    orderDirection?: QueryOrderDirection;
    pageIndex?: number;
    pageSize?: number;
    searchPattern?: string;
    signatureTitleShort?: string;
    tagTitle?: string;
};

export type NewsGetPagedListResponse = NewsListItemDtoIPagedList;

export type NewsCategoryGetPagedListResponse = NewsCategoryListItemDtoIPagedList;

export type NewsSignatureGetPagedListResponse = NewsSignatureListItemDtoIPagedList;

export type NewsSignatureCreateData = {
    requestBody?: NewsSignatureCreateDto;
};

export type NewsSignatureCreateResponse = ApiSuccessResponse;

export type NewsSignatureUpdateData = {
    requestBody?: NewsSignatureUpdateDto;
};

export type NewsSignatureUpdateResponse = ApiSuccessResponse;

export type NewsSignatureRemoveData = {
    id: string;
};

export type NewsSignatureRemoveResponse = ApiSuccessResponse;

export type NewsTagGetPagedListResponse = NewsTagListItemDtoIPagedList;

export type UploadsGetFileData = {
    onlyFilterVisible?: boolean;
};

export type UploadsGetFileResponse = Array<unknown>;

export type $OpenApiTs = {
    '/admin/api/News': {
        get: {
            req: NewsGetPagedListData;
            res: {
                /**
                 * OK
                 */
                200: NewsListItemDtoIPagedList;
                /**
                 * Bad Request
                 */
                400: ApiErrorResponse;
                /**
                 * Internal Server Error
                 */
                500: ApiErrorResponse;
            };
        };
    };
    '/admin/api/NewsCategory': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: NewsCategoryListItemDtoIPagedList;
                /**
                 * Bad Request
                 */
                400: ApiErrorResponse;
                /**
                 * Internal Server Error
                 */
                500: ApiErrorResponse;
            };
        };
    };
    '/admin/api/NewsSignature': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: NewsSignatureListItemDtoIPagedList;
                /**
                 * Bad Request
                 */
                400: ApiErrorResponse;
                /**
                 * Internal Server Error
                 */
                500: ApiErrorResponse;
            };
        };
        post: {
            req: NewsSignatureCreateData;
            res: {
                /**
                 * OK
                 */
                200: ApiSuccessResponse;
                /**
                 * Bad Request
                 */
                400: ApiErrorResponse;
                /**
                 * Internal Server Error
                 */
                500: ApiErrorResponse;
            };
        };
        put: {
            req: NewsSignatureUpdateData;
            res: {
                /**
                 * OK
                 */
                200: ApiSuccessResponse;
                /**
                 * Bad Request
                 */
                400: ApiErrorResponse;
                /**
                 * Internal Server Error
                 */
                500: ApiErrorResponse;
            };
        };
    };
    '/admin/api/NewsSignature/{id}': {
        delete: {
            req: NewsSignatureRemoveData;
            res: {
                /**
                 * OK
                 */
                200: ApiSuccessResponse;
                /**
                 * Bad Request
                 */
                400: ApiErrorResponse;
                /**
                 * Internal Server Error
                 */
                500: ApiErrorResponse;
            };
        };
    };
    '/admin/api/NewsTag': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: NewsTagListItemDtoIPagedList;
                /**
                 * Bad Request
                 */
                400: ApiErrorResponse;
                /**
                 * Internal Server Error
                 */
                500: ApiErrorResponse;
            };
        };
    };
    '/Uploads': {
        get: {
            req: UploadsGetFileData;
            res: {
                /**
                 * OK
                 */
                200: Array<unknown>;
                /**
                 * Bad Request
                 */
                400: ApiErrorResponse;
                /**
                 * Internal Server Error
                 */
                500: ApiErrorResponse;
            };
        };
    };
};